# MkDocs Configuration for AgentVault

site_name: AgentVault Documentation
site_url: https://SecureAgentTools.github.io/AgentVault/
repo_url: https://github.com/SecureAgentTools/AgentVault/
repo_name: AgentVault
edit_uri: "" # Disable edit button for now

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.copy
    - content.code.annotate
    - mermaid
  palette:
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  # logo: assets/logo.png # Add logo later if desired

plugins:
  - search # Enable search plugin

nav:
  - Home: index.md
  - Vision: vision.md
  - Introduction:
    - Concepts: concepts.md
    - Architecture: architecture.md
    - Use Cases: use_cases.md
  - Installation: installation.md # Link to Registry Setup will be added here
  - Examples:
      - Overview: examples/index.md # Link to the new overview page
      - Basic Agents: examples/basic_agents.md # New page for simple examples
      - LangChain Tool: examples/langchain_integration.md
      - Pipelines (POCs):
          - Research Pipeline: examples/poc_research.md
          - Support Ticket Pipeline: examples/poc_support.md
          - Dynamics 365 Pipeline: examples/poc_dynamics.md
          - E-commerce Pipeline: examples/poc_ecommerce.md
          - ETL Pipeline: examples/poc_etl.md
          - MCP Test Pipeline: examples/poc_mcp_pipeline.md
  - User Guide:
    - CLI Usage: user_guide/cli.md
  - Developer Guide:
    - Client Library (`agentvault`): developer_guide/library.md
    - Server SDK (`agentvault-server-sdk`): developer_guide/server_sdk.md
    # --- CORRECTED LINE 60 ---
    - 'Registry: Setup & API': developer_guide/registry.md # <-- Enclosed title in quotes
    # --- END CORRECTION ---
    - Testing Utilities (`agentvault-testing-utils`): developer_guide/testing.md
  - Protocols:
    - A2A Profile v0.2: a2a_profile_v0.2.md
    - MCP Profile (Concept): mcp.md
    - TEE Profile: tee_profile.md
  - Project & Policies:
    - Contributing: CONTRIBUTING.md
    - Code of Conduct: CODE_OF_CONDUCT.md
    - Security: security.md
    - Security Policy: security_policy.md
    - Registry Policy: REGISTRY_POLICY.md
    - Terms of Service: TERMS_OF_SERVICE.md
    - Privacy Policy: privacy_policy.md
    - Roadmap: ROADMAP.md

# Source directory for markdown files
docs_dir: 'docs'

# Optional: Add markdown extensions for enhanced formatting
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - toc:
      permalink: true
      toc_depth: 3 # Adjust depth as needed
  - attr_list # Allows adding classes/ids to markdown elements
  - md_in_html # Allows markdown processing inside HTML blocks

# Copyright notice (optional)
# copyright: Copyright © 2025 AgentVault Contributors
