[project]
name = "agentvault"
version = "0.1.0"
description = ""
authors = [{ name = "Your Name", email = "you@example.com" }]
requires-python = ">=3.10,<3.12"
dependencies = [
    "httpx>=0.27,<0.28",
    "pydantic>=2.0,<3.0"
]

[tool.poetry.group.dev]
[tool.poetry.group.dev.dependencies]
pytest = "^7.0.0"
# Add other development dependencies as needed

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"