[project]
    name = "agentvault"
    version = "0.1.0"
    description = "Core Python client library for A2A protocol, MCP, and secure local key management." # Added description
    authors = [{ name = "Your Name", email = "you@example.com" }] # Replace with actual details
    license = "Apache-2.0" # Added license field
    readme = "README.md" # Added readme field

    requires-python = ">=3.10,<3.12"

    # Core Dependencies
    dependencies = [
        # httpx extras specified here for standard build if needed
        "httpx[http2,brotli]>=0.27,<0.28",
        "pydantic>=2.0,<3.0",
        "python-dotenv>=1.0,<2.0"
        # keyring is optional, handled via extras
    ]

    # Optional dependencies defined as extras
    [project.optional-dependencies]
    os_keyring = ["keyring>=24,<25"]

    [build-system]
    requires = ["poetry-core>=1.0.0"]
    build-backend = "poetry.core.masonry.api"

    # --- Poetry Specific Configuration ---
    [tool.poetry]
    name = "agentvault"
    version = "0.1.0"
    description = "Core Python client library for A2A protocol, MCP, and secure local key management."
    authors = ["Your Name <you@example.com>"] # Replace with actual details
    license = "Apache-2.0"
    readme = "README.md"
    packages = [{include = "agentvault", from = "src"}]

    [tool.poetry.dependencies]
    python = ">=3.10,<3.12"
    httpx = {version = ">=0.27,<0.28", extras = ["http2", "brotli"]}
    pydantic = ">=2.0,<3.0"
    python-dotenv = ">=1.0,<2.0"
    keyring = {version = ">=24,<25", optional = true} # Define optional dep here

    # Define extras for Poetry
    [tool.poetry.extras]
    os_keyring = ["keyring"]

    # Development dependencies
    [tool.poetry.group.dev.dependencies]
    pytest = ">=7.0,<9.0"
    pytest-asyncio = ">=0.23,<0.24" # Ensure this is present
    pytest-mock = ">=3.12,<4.0"
    respx = ">=0.20,<0.21" # Ensure this is present

    #
