# --- START OF FILE: agentvault_cli/pyproject.toml ---
[project]
name = "agentvault-cli"
version = "0.1.0"
description = "Command-line client for the AgentVault ecosystem."
authors = [{ name = "Raphael Zbigniew Jeziorny", email = "AgentVault@proton.me" }]
requires-python = ">=3.10,<3.12"
license = "Apache-2.0"
readme = "README.md"

# List only simple string dependencies here for PEP 621 compatibility
dependencies = [
    "click>=8.0,<9.0",
    "httpx>=0.27,<0.28",
    "rich>=13.0,<15.0"
]

[project.scripts]
agentvault_cli = "agentvault_cli.main:cli"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

# --- Poetry Specific Configuration ---
[tool.poetry]
# Metadata can be inferred from [project], but defining packages and dependencies here is crucial

# Define the package location(s) using the standard array format
packages = [
    { include = "agentvault_cli", from = "src" },
]

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
click = ">=8.0,<9.0"
httpx = ">=0.27,<0.28"
rich = ">=13.0,<15.0"
# Define the path dependency here
agentvault = { path = "../agentvault_library", develop = true }

# Development dependencies
[tool.poetry.group.dev.dependencies]
pytest = ">=7.0,<9.0"
pytest-mock = ">=3.12,<4.0"

# --- END OF FILE: agentvault_cli/pyproject.toml ---