name: Deploy Documentation to GitHub Pages

# Trigger the workflow on push events to the main branch
on:
  push:
    branches:
      - main # Or your default branch name

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write # Allow peaceiris/actions-gh-pages to push to the gh-pages branch

jobs:
  deploy:
    runs-on: ubuntu-latest # Use a standard Linux runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Use latest checkout action

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # Use a Python version compatible with MkDocs & plugins
          cache: 'pip' # Cache pip dependencies

      - name: Install MkDocs and Material Theme
        run: pip install mkdocs mkdocs-material

      # If your docs reference code from the project (e.g., via mkdocstrings),
      # you might need to install the project itself here too.
      # - name: Install Project Dependencies (Optional)
      #   run: pip install . # Or specific components if needed

      - name: Build MkDocs site
        run: mkdocs build # Builds the site into the default 'site/' directory

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4 # Use latest deploy action
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site # Directory containing the built site
          # Optional: Specify a custom domain if you have one configured
          # cname: docs.example.com
